---
- name: Install and configure Prometheus, Grafana and Alertmanager in Docker
  hosts: all
  gather_facts: false
  become: true
  vars:
    enable_blackbox: true
    enable_idrac: true
  vars_files:
    - inventory/group_vars/all.yml
    - targets_vars.yml
    - vault_vars.yml

  roles:
    - role: docker
      tags: docker

    - role: prometheus
      tags: prometheus

    - role: grafana
      tags: grafana

    - role: alertmanager
      tags: alertmanager

    - role: node_exporter
      tags: node_exporter

    - role: blackbox_exporter
      tags: blackbox_exporter
      when: enable_blackbox | bool

    - role: idrac_exporter
      tags: idrac_exporter
      when: enable_idrac | bool

    - role: nginx
      tags: nginx
...
