- name: Create Node Exporter user
  user:
    name: node_exporter
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present
  register: node_exporter_user
  tags: node_exporter

- name: Get UID and GID for node_exporter user
  set_fact:
    node_exporter_uid: "{{ node_exporter_user.uid }}"
    node_exporter_gid: "{{ node_exporter_user.group }}"
  tags: node_exporter

- name: Create Docker network for monitoring
  docker_network:
    name: "{{ docker_network }}"
    state: present
  tags: node_exporter

- name: Run Node Exporter container
  docker_container:
    name: node_exporter
    user: "{{ node_exporter_uid }}:{{ node_exporter_gid }}"
    image: prom/node-exporter:{{ node_exporter_version }}
    ports:
      - "{{ node_exporter_port }}:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - name: "{{ docker_network }}"
    restart_policy: always
  tags: node_exporter
