---
- name: Create Prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present
  register: prometheus_user
  tags: prometheus

- name: Get UID and GID for prometheus user
  set_fact:
    prometheus_uid: "{{ prometheus_user.uid }}"
    prometheus_gid: "{{ prometheus_user.group }}"
  tags: prometheus

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
  tags: prometheus

- name: Copy prometheus config files
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - prometheus.yml
  notify: Restart prometheus
  tags: prometheus

- name: Copy prometheus rules
  copy:
    src: "files/{{ item }}"
    dest: "/etc/prometheus/{{ item }}"
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - rules.yml
  notify: Restart prometheus
  tags: prometheus  

- name: Create Docker network for monitoring
  docker_network:
    name: "{{ docker_network }}"
    state: present
  tags: prometheus

- name: Run Prometheus container
  docker_container:
    name: prometheus
    user: "{{ prometheus_uid }}:{{ prometheus_gid }}"
    image: prom/prometheus:{{ prometheus_version }}
    ports:
      - "{{ prometheus_port }}:9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - /var/lib/prometheus:/prometheus
    networks:
      - name: "{{ docker_network }}"
    restart_policy: always
  tags: prometheus

- name: Restart prometheus
  meta: flush_handlers
  tags: prometheus
