prometheus_version: "v2.55.1"
grafana_version: "10.2.1"
alertmanager_version: "v0.26.0"
node_exporter_version: "v1.8.2"

prometheus_port: 9090
grafana_port: 3000
alertmanager_port: 9093
node_exporter_port: 9100

docker_network: "monitoring_net"

